/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCarSelect: typeof import('./src/components/add/SelectCar.vue')['default']
    AddIcon: typeof import('./src/components/icons/AddIcon.vue')['default']
    Button: typeof import('./src/components/buttons/Button.vue')['default']
    ButtonSecondary: typeof import('./src/components/buttons/ButtonSecondary.vue')['default']
    CarBox: typeof import('./src/components/car/CarBox.vue')['default']
    CarCreate: typeof import('./src/components/car/CarCreate.vue')['default']
    CarIcon: typeof import('./src/components/icons/CarIcon.vue')['default']
    CarSelect: typeof import('./src/components/add/CarSelect.vue')['default']
    copy: typeof import('./src/components/interventions/InterventionBox copy.vue')['default']
    CurUserIcon: typeof import('./src/components/icons/CurUserIcon.vue')['default']
    ExploreContainer: typeof import('./src/components/ExploreContainer.vue')['default']
    HomeIcon: typeof import('./src/components/icons/HomeIcon.vue')['default']
    InterventionBox: typeof import('./src/components/interventions/InterventionBox.vue')['default']
    InterventionFacture: typeof import('./src/components/interventions/InterventionFacture.vue')['default']
    ListIcon: typeof import('./src/components/icons/ListIcon.vue')['default']
    LoadingWrapper: typeof import('./src/components/animations/LoadingWrapper.vue')['default']
    Menu2Icon: typeof import('./src/components/icons/Menu2Icon.vue')['default']
    MenuIcon: typeof import('./src/components/icons/MenuIcon.vue')['default']
    NotificationBox: typeof import('./src/components/notifications/NotificationBox.vue')['default']
    NotificationIcon: typeof import('./src/components/icons/NotificationIcon.vue')['default']
    PayIcon: typeof import('./src/components/icons/PayIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCar: typeof import('./src/components/add/SelectCar.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    TextInput: typeof import('./src/components/input/TextInput.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAuthForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UColorPicker: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UPageCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UPinInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    UserBtn: typeof import('./src/components/buttons/UserBtn.vue')['default']
    UserIcon: typeof import('./src/components/icons/UserIcon.vue')['default']
    UTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    WaitListIcon: typeof import('./src/components/icons/WaitListIcon.vue')['default']
  }
}
