/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddIcon: typeof import('./src/components/icons/AddIcon.vue')['default']
    Button: typeof import('./src/components/buttons/Button.vue')['default']
    ButtonSecondary: typeof import('./src/components/buttons/ButtonSecondary.vue')['default']
    CarBox: typeof import('./src/components/box/CarBox.vue')['default']
    CarIcon: typeof import('./src/components/icons/CarIcon.vue')['default']
    CurUserIcon: typeof import('./src/components/icons/CurUserIcon.vue')['default']
    ExploreContainer: typeof import('./src/components/ExploreContainer.vue')['default']
    HomeIcon: typeof import('./src/components/icons/HomeIcon.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InterventionBox: typeof import('./src/components/box/InterventionBox.vue')['default']
    ListIcon: typeof import('./src/components/icons/ListIcon.vue')['default']
    LoadingWrapper: typeof import('./src/components/animations/LoadingWrapper.vue')['default']
    Menu2Icon: typeof import('./src/components/icons/Menu2Icon.vue')['default']
    MenuIcon: typeof import('./src/components/icons/MenuIcon.vue')['default']
    NotificationBox: typeof import('./src/components/box/NotificationBox.vue')['default']
    NotificationIcon: typeof import('./src/components/icons/NotificationIcon.vue')['default']
    PayIcon: typeof import('./src/components/icons/PayIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./src/components/input/TextInput.vue')['default']
    UserBtn: typeof import('./src/components/buttons/UserBtn.vue')['default']
    UserIcon: typeof import('./src/components/icons/UserIcon.vue')['default']
    WaitListIcon: typeof import('./src/components/icons/WaitListIcon.vue')['default']
  }
}
