/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddIcon: typeof import('./src/components/icons/AddIcon.vue')['default']
    AlertIcon: typeof import('./src/components/icons/AlertIcon.vue')['default']
    Button: typeof import('./src/components/buttons/Button.vue')['default']
    ButtonSecondary: typeof import('./src/components/buttons/ButtonSecondary.vue')['default']
    Car2Icon: typeof import('./src/components/icons/Car2Icon.vue')['default']
    CarBox: typeof import('./src/components/car/CarBox.vue')['default']
    CarCreate: typeof import('./src/components/car/CarCreate.vue')['default']
    CarIcon: typeof import('./src/components/icons/CarIcon.vue')['default']
    CartIcon: typeof import('./src/components/icons/CartIcon.vue')['default']
    CurUserIcon: typeof import('./src/components/icons/CurUserIcon.vue')['default']
    DrillIcon: typeof import('./src/components/icons/DrillIcon.vue')['default']
    EmptyRecuperation: typeof import('./src/components/empty/EmptyRecuperation.vue')['default']
    ExploreContainer: typeof import('./src/components/ExploreContainer.vue')['default']
    HomeIcon: typeof import('./src/components/icons/HomeIcon.vue')['default']
    InterventionBox: typeof import('./src/components/interventions/InterventionBox.vue')['default']
    InterventionFacture: typeof import('./src/components/interventions/InterventionFacture.vue')['default']
    ListIcon: typeof import('./src/components/icons/ListIcon.vue')['default']
    LoadingWrapper: typeof import('./src/components/animations/LoadingWrapper.vue')['default']
    MainWrapper: typeof import('./src/components/wrapper/MainWrapper.vue')['default']
    Menu2Icon: typeof import('./src/components/icons/Menu2Icon.vue')['default']
    MenuIcon: typeof import('./src/components/icons/MenuIcon.vue')['default']
    NotificationBox: typeof import('./src/components/notifications/NotificationBox.vue')['default']
    NotificationIcon: typeof import('./src/components/icons/NotificationIcon.vue')['default']
    PayForm: typeof import('./src/components/pay/PayForm.vue')['default']
    PayIcon: typeof import('./src/components/icons/PayIcon.vue')['default']
    ReparationBox: typeof import('./src/components/reparations/ReparationBox.vue')['default']
    ReparationsList: typeof import('./src/components/reparations/ReparationsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCar: typeof import('./src/components/add/SelectCar.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    TextInput: typeof import('./src/components/input/TextInput.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UserBtn: typeof import('./src/components/buttons/UserBtn.vue')['default']
    UserIcon: typeof import('./src/components/icons/UserIcon.vue')['default']
    WaitListIcon: typeof import('./src/components/icons/WaitListIcon.vue')['default']
  }
}
